apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
commonLabels:
  env: dev
patches:
- path: new-image.yaml
  target:
    kind: Deployment
    name: flask-deployment
- path: service.yaml
  target:
    kind: Service
    name: frontend-service
images:
- name: 389099493521.dkr.ecr.eu-central-1.amazonaws.com/flask-app 
  newName: nginx
  newTag: latest
